language: haskell
ghc:
  - 7.6
  - 7.8
install:
  - cabal update
  - cabal sandbox init
  - cabal install --only-dependencies --enable-tests --enable-benchmarks
script:
  - cabal configure --enable-tests --enable-benchmarks -v2
  - cabal build
  - cabal test
  - cabal sdist


