language: haskell
ghc:
  - 7.6
  - 7.8
script:
  - cabal update
  - cabal install cabal-install
  - cabal sandbox init
  - cabal configure --enable-tests --enable-benchmarks --enable-library-coverage
  - cabal install --only-dependencies
  - cabal build
  - cabal test


